# 2018-11-10 21:40:41.928603
from alembic import op
import sqlalchemy as sa


revision = '6c70aadc468b'
down_revision = '668575cc4adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
